## Working with stock market data with the OpenBB Platform

In [1]:
from IPython.display import display
from openbb import obb

Extensions to add: alpha_vantage@1.4.0, biztoc@1.4.0, cboe@1.4.0, deribit@1.0.0, ecb@1.4.0, econometrics@1.5.1, finra@1.4.0, finviz@1.3.0, fixedincome@1.4.1, government_us@1.4.0, multpl@1.1.0, nasdaq@1.4.0, openbb_charting@2.3.1, quantitative@1.4.1, seeking_alpha@1.4.0, stockgrid@1.4.0, technical@1.4.1, tmx@1.3.0, tradier@1.3.0, wsj@1.4.0, yfinance@1.4.1
Extensions to remove: fixedincome@1.4.0, yfinance@1.4.0

Building...

In [2]:
obb.user.preferences.output_type = "dataframe"

Fetches historical price data for the equity "SPY" using the "yfinance" provider and displays the first 10 rows

In [3]:
data = obb.equity.price.historical("SPY", provider="yfinance")

In [ ]:
display(data.head(10))

                  open        high         low       close    volume  dividend
date
2024-02-20  497.720001  498.410004  494.450012  496.760010  71736700       0.0
2024-02-21  495.420013  497.369995  493.559998  497.209991  59603800       0.0
2024-02-22  504.010010  508.489990  503.019989  507.500000  76402500       0.0
2024-02-23  509.269989  510.130005  507.100006  507.850006  61321800       0.0
2024-02-26  508.299988  508.750000  505.859985  505.989990  50386700       0.0
2024-02-27  506.700012  507.160004  504.750000  506.929993  48854500       0.0
2024-02-28  505.329987  506.859985  504.959991  506.260010  56506600       0.0
2024-02-29  508.070007  509.739990  505.350006  508.079987  83924800       0.0
2024-03-01  508.980011  513.289978  508.559998  512.849976  76805900       0.0
2024-03-04  512.030029  514.200012  512.000000  512.299988  49799300       0.0

Fetches fundamental metrics for the equities "AAPL" and "MSFT" using the "yfinance" provider and transposes the dataframe

In [5]:
data = obb.equity.fundamental.metrics("AAPL,MSFT", provider="yfinance")

In [6]:
display(data.T)

                                         0                1
symbol                                AAPL             MSFT
market_cap                 3678461755392.0  3083391729664.0
pe_ratio                         38.930046        33.449192
forward_pe                       29.466906        27.743813
peg_ratio_ttm                       2.2679            2.162
enterprise_to_ebitda                27.094           21.929
earnings_growth                      0.101            0.102
earnings_growth_quarterly            0.071            0.102
revenue_per_share                   25.974           35.224
revenue_growth                        0.04            0.123
enterprise_to_revenue                9.403           11.897
quick_ratio                          0.783            1.204
current_ratio                        0.923            1.351
debt_to_equity                       145.0           33.998
gross_margin                       0.46519          0.69409
operating_margin                   0.34459          0.45458
ebitda_margin                      0.34706          0.54255
profit_margin                      0.24295          0.35428
return_on_assets                   0.22519          0.14649
return_on_equity                    1.3652          0.34291
dividend_yield                        0.41              0.8
dividend_yield_5y_avg                0.006           0.0086
payout_ratio                        0.1571           0.2482
book_value                           4.438           40.712
price_to_book                     55.17575        10.187904
enterprise_value             3721479061504    3114746773504
overall_risk                           1.0              3.0
audit_risk                             3.0              9.0
board_risk                             1.0              5.0
compensation_risk                      3.0              3.0
shareholder_rights_risk                1.0              2.0
beta                                   1.2            0.895
price_return_1y                   0.328145         0.007579
currency                               USD              USD

Fetches valuation metrics for industries using the "finviz" provider and displays the data

In [7]:
data = obb.equity.compare.groups(
    group="industry", metric="valuation", provider="finviz"
)

In [8]:
display(data)

,name,market_cap,performance_1d,pe,forward_pe,peg,eps_growth_past_5y,eps_growth_next_5y,volume,price_to_sales,price_to_book,price_to_free_cash_flow,sales_growth_past_5_years,price_to_cash
0,Insurance - Reinsurance,43680000000,-0.0076,10.03,6.39,0.63,0.0520,0.1597,2520000,0.78,1.11,2.26,0.1700,NaN
1,Coking Coal,6070000000,-0.0254,8.31,6.76,NaN,0.0468,-0.1107,2640000,0.81,1.28,8.77,0.1833,5.04
2,Paper & Paper Products,17210000000,-0.0054,58.80,7.13,NaN,-0.1291,NaN,2440000,0.97,2.02,13.69,0.0731,4.00
3,Pharmaceutical Retailers,9670000000,-0.0237,NaN,7.49,NaN,0.4817,-0.1660,22890000,0.06,0.94,477.00,0.0361,7.35
4,REIT - Mortgage,62520000000,0.0010,13.07,7.61,12.63,-0.0240,0.0103,60300000,1.84,0.90,9.67,0.2606,4.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140,REIT - Healthcare Facilities,180690000000,-0.0048,100.22,56.53,9.09,-0.0639,0.1102,29300000,7.45,2.21,29.89,0.1507,27.74
141,REIT - Office,82730000000,-0.0089,90.24,56.98,0.66,-0.3157,1.3632,24970000,4.20,1.25,15.07,0.0460,9.89
142,Real Estate - Diversified,6700000000,-0.0542,44.11,125.73,NaN,0.1855,NaN,3240000,4.11,1.88,30.91,0.1891,6.41
143,Infrastructure Operations,36510000000,-0.0130,39.66,171.08,3.38,NaN,0.1174,961320,3.49,7.77,34.16,0.0934,8.80
144,Shell Companies,31640000000,-0.0018,206.70,NaN,NaN,NaN,NaN,39170000,14.78,3.43,NaN,-0.0075,57.09

Fetches performance metrics for industries using the "finviz" provider and displays the data

In [9]:
data = obb.equity.compare.groups(
    group="industry", metric="performance", provider="finviz"
)

In [10]:
display(data)

,name,performance_1d,performance_1w,performance_1m,performance_3m,performance_6m,performance_1y,performance_ytd,analyst_recommendation,volume,volume_average,volume_relative
0,Coking Coal,-0.0254,-0.0860,-0.1185,-0.2706,-0.2073,-0.3911,-0.1296,2.02,2640000,2760000,0.96
1,Uranium,-0.0321,-0.0707,-0.0936,-0.1350,0.1568,-0.0006,-0.0756,1.22,108480000,63780000,1.70
2,Oil & Gas Drilling,-0.0295,-0.0579,-0.1382,-0.1475,-0.2137,-0.2638,-0.0775,1.97,55790000,43900000,1.27
3,Thermal Coal,-0.0125,-0.0536,-0.1386,-0.2666,-0.0872,-0.0023,-0.1711,1.48,6750000,4670000,1.44
4,Home Improvement Retail,-0.0189,-0.0470,-0.0396,-0.0425,0.0693,0.0852,0.0112,2.05,10080000,8670000,1.16
...,...,...,...,...,...,...,...,...,...,...,...,...
140,Auto Manufacturers,0.0077,0.0686,-0.1036,0.1147,0.3677,0.2536,-0.0772,2.43,362830000,401490000,0.90
141,Luxury Goods,0.0075,0.0704,0.1535,0.2901,0.5488,0.2494,0.1843,2.06,13880000,14400000,0.96
142,Resorts & Casinos,0.0011,0.0714,0.0459,-0.0304,0.0959,-0.1230,-0.0165,1.80,27560000,30460000,0.90
143,Gambling,-0.0056,0.0904,0.1420,0.1080,0.2937,0.2388,0.1607,1.40,27900000,28490000,0.98
144,Pharmaceutical Retailers,-0.0237,0.1453,-0.1392,0.2054,-0.0090,-0.5063,0.1399,2.81,22890000,27120000,0.84

Fetches overview metrics for industries using the "finviz" provider and displays the data

In [11]:
data = obb.equity.compare.groups(group="industry", metric="overview", provider="finviz")

In [12]:
display(data)

,name,market_cap,performance_1d,dividend_yield,pe,forward_pe,float_short,volume,Stocks,peg
0,Real Estate - Diversified,6700000000,-0.0542,0.0045,44.11,125.73,0.0233,3240000,4,NaN
1,Chemicals,49770000000,-0.0446,0.0490,30.63,12.00,0.0388,34720000,17,1.48
2,Real Estate - Development,9340000000,-0.0363,0.0154,8.98,11.71,0.0357,2040000,15,NaN
3,Uranium,31460000000,-0.0321,0.0016,121.35,49.34,0.0798,108480000,9,4.29
4,Oil & Gas Drilling,20130000000,-0.0295,0.0329,15.12,11.97,0.1351,55790000,9,0.97
...,...,...,...,...,...,...,...,...,...,...
140,Beverages - Non-Alcoholic,681860000000,0.0132,0.0285,25.42,19.92,0.0182,71970000,17,3.71
141,Oil & Gas E&P,726460000000,0.0183,0.0310,12.87,11.58,0.0359,223530000,88,1.74
142,Real Estate Services,153630000000,0.0204,0.0057,54.29,22.09,0.0505,115290000,48,2.69
143,Healthcare Plans,813530000000,0.0206,0.0200,24.14,12.48,0.0226,39730000,11,1.98
144,Scientific & Technical Instruments,210610000000,0.0306,0.0047,31.79,21.63,0.0503,65150000,32,2.17

**Jason Strimpel** is the founder of <a href='https://pyquantnews.com/'>PyQuant News</a> and co-founder of <a href='https://www.tradeblotter.io/'>Trade Blotter</a>. His career in algorithmic trading spans 20+ years. He previously traded for a Chicago-based hedge fund, was a risk manager at JPMorgan, and managed production risk technology for an energy derivatives trading firm in London. In Singapore, he served as APAC CIO for an agricultural trading firm and built the data science team for a global metals trading firm. Jason holds degrees in Finance and Economics and a Master's in Quantitative Finance from the Illinois Institute of Technology. His career spans America, Europe, and Asia. He shares his expertise through the <a href='https://pyquantnews.com/subscribe-to-the-pyquant-newsletter/'>PyQuant Newsletter</a>, social media, and has taught over 1,000+ algorithmic trading with Python in his popular course **<a href='https://gettingstartedwithpythonforquantfinance.com/'>Getting Started With Python for Quant Finance</a>**. All code is for educational purposes only. Nothing provided here is financial advise. Use at your own risk.